### ISSUE TITLE
Customize classes ?

### ISSUE THREAD

**Issue by lgodard** [antoinebeland/d3-simple-gauge#1]
Hi,
I plan to use the package but would need to have different gauges in a same page with different colors, so different classes settings
Is there any way to pass self-named classes as argument ?
Any evolution possible in the module ? I may help

**Comment by antoinebeland** [comment]
Hi @lgodard,

For the moment, it is not possible to define custom class names as arguments. The modification can be easily done in the code to support this new feature. However, I think that it's not necessary to add this feature because you can manage easily different styles like this:

```js
const svg = d3.select('body')
  .append('svg')
  .attr('width', 400)
  .attr('height', 250);

const simpleGaugeGroup = svg.append('g')
  .attr('class', 'gauge-group1'); // I put custom class on the gauge group.

const simpleGauge = new window.d3SimpleGauge.SimpleGauge({
  el: simpleGaugeGroup,  // The element that hosts the gauge
  height: 200,                
  sectionsCount: 2,
  width: 400
});
```
In your CSS code, you can define the specific style for the `gauge-group1` like this:
```css
/* Specific colors for the gauge-group1 */

.gauge-group1 .chart-color1 {
  fill: #f00;
}
.gauge-group1 .chart-color2 {
  fill: #0f0;
}
/* ... */
```

Let me know what you think about this approach. I can do the modification too to support custom class names in the code.
